# Use the official Golang image as a parent image
FROM golang:1.23-alpine AS builder

# Set the working directory inside the container
WORKDIR /go/src/app

# Copy the entire workspace
COPY . .

# Download all dependencies
RUN go mod download

# Build the application from the cmd_server directory
RUN cd cmd_server && go build -o /go/bin/cmd_server

# Use a smaller base image for the final stage
FROM alpine:latest

# Set the working directory
WORKDIR /root/

# Copy the binary from the builder stage
COPY --from=builder /go/bin/cmd_server .

# Command to run the executable
CMD ["./cmd_server"]
