name: Build and Release

on:
  pull_request:
    branches: [main]  # Adjust this if your main branch has a different name
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Build cmd_server
        run: |
          cd cmd_server
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o ../cmd_server-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}

      - name: Build cmd_worker
        run: |
          cd cmd_worker
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o ../cmd_worker-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries-${{ matrix.goos }}-${{ matrix.goarch }}
          path: |
            cmd_server-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}
            cmd_worker-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}

  release:
    name: Release
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v2

      - name: Release binaries
        uses: softprops/action-gh-release@v1
        with:
          files: binaries-*/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
